version: '3.7'

services:
  medusa:
    build: .
    ports:
      - "9001:9000"  # Changed to avoid conflict
    environment:
      DATABASE_URL: postgres://postgres:medusadb@postgres:5432/medusa1?sslmode=require&rejectUnauthorized=false
      REDIS_URL: redis://redis:6379
      NODE_TLS_REJECT_UNAUTHORIZED: '0'  # Allows self-signed certificates
    depends_on:
      - postgres
      - redis
    networks:
      - my_network

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres-ssl
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medusadb
      POSTGRES_DB: medusa1
    ports:
      - "5433:5432"  # Changed to avoid conflict
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-certs:/var/lib/postgresql/certs
    networks:
      - my_network

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"  # Changed to avoid conflict
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres-data:
  postgres-certs:
