version: '3.7'

services:
  medusa:
    build: .
    ports:
      - "9001:9000"  # Exposing Medusa on port 9001 externally
    environment:
      DATABASE_URL: postgres://postgres:medusadb@postgres:5432/medusa1?sslmode=require&rejectUnauthorized=false
      REDIS_URL: redis://redis:6379
      NODE_TLS_REJECT_UNAUTHORIZED: '0'  # Allows self-signed certificates
      STORE_CORS: https://medusa1-medusa-project3.knjmqz.easypanel.host
      ADMIN_CORS: https://medusa1-medusa-project3.knjmqz.easypanel.host
      AUTH_CORS: https://medusa1-medusa-project3.knjmqz.easypanel.host
    depends_on:
      - postgres
      - redis
    networks:
      - my_network

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres-ssl  # Make sure this file exists for custom Postgres with SSL setup
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medusadb
      POSTGRES_DB: medusa1
    ports:
      - "5433:5432"  # Changed to avoid conflict with local Postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-certs:/var/lib/postgresql/certs  # SSL certificates
    networks:
      - my_network

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"  # Changed to avoid conflict with local Redis
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres-data:
  postgres-certs:
